export const defaultTopics = [
  'Negotiations and deals',
  'Advertising and branding',
  'Entrepreneurship and startups',
  'Leadership and management',
  'Sustainable energy',
  'Social media and influencer marketing',
  'Virtual and augmented reality',
  'Artificial intelligence and machine learning',
  'Cryptocurrency and blockchain',
  'E-commerce and online shopping',
  'Globalization and world affairs',
  'Diversity and inclusion',
  'Public speaking and presentations',
  'Travel and tourism',
  'Film and cinema',
  'Literature and poetry',
  'Music and concerts',
  'Sports and fitness',
  'Food and cooking',
  'Fashion and trends'
]

export const defaultWords = [
  'dog',
  'cat',
  'elephant',
  'tiger',
  'lion',
  'giraffe',
  'zebra',
  'bear',
  'monkey',
  'hippopotamus',
  'rhinoceros',
  'kangaroo',
  'penguin',
  'crocodile',
  'snake',
  'wolf',
  'fox',
  'deer',
  'rabbit',
  'owl',
  'beach',
  'mountain',
  'sightseeing',
  'adventure',
  'culture',
  'explore',
  'vacation',
  'camera',
  'passport',
  'hiking',
  'scenic',
  'tourism'
]
